#端口，项目上下文根
#其中context-path: /hotel可以不用配置
#如果配置，访问路径就是http://ip:port/hotel/
#没有配置，访问路径就是http://ip:port/
server:
  port: 8080
  servlet:
    context-path: /hotel

#数据库配置
#mysql configure
spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    dynamic:
      primary: db-food
      datasource:
        db-live-ali:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.1.192:3306/live?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
          # 动态切换数据库用的
          jdbc-url: jdbc:mysql://192.168.1.192:3306/live?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull
          username: food
          password: food0563
          minimum-idle: 1
          maximum-pool-size: 5
          max-wait: 3600
          tomcat:
            init-s-q-l: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci

